export { default } from "./src/wallet-manager-evm.js";
export { default as WalletAccountReadOnlyEvm } from "./src/wallet-account-read-only-evm.js";
export { default as WalletAccountEvm } from "./src/wallet-account-evm.js";
export type EvmTransactionReceipt = import("ethers").TransactionReceipt;
export type TypedData = import("./src/wallet-account-read-only-evm.js").TypedData;
export type TypedDataDomain = import("./src/wallet-account-read-only-evm.js").TypedDataDomain;
export type TypedDataField = import("./src/wallet-account-read-only-evm.js").TypedDataField;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type EvmTransaction = import("./src/wallet-account-read-only-evm.js").EvmTransaction;
export type EvmWalletConfig = import("./src/wallet-account-read-only-evm.js").EvmWalletConfig;
export type ApproveOptions = import("./src/wallet-account-evm.js").ApproveOptions;
export type EvmTransferOptions = import("./src/wallet-account-evm.js").EvmTransferOptions;
export type Erc7702AuthorizationRequest = import("./src/wallet-account-read-only-evm.js").Erc7702AuthorizationRequest;
export type Erc7702Authorization = import("./src/wallet-account-read-only-evm.js").Erc7702Authorization;
export type DelegationInfo = import("./src/wallet-account-read-only-evm.js").DelegationInfo;
