export { default } from "./src/wallet-manager-evm.js";
export { default as WalletAccountReadOnlyEvm } from "./src/wallet-account-read-only-evm.js";
export { default as WalletAccountEvm } from "./src/wallet-account-evm.js";
export { ISigner } from "@tetherto/wdk-wallet";
export type TypedDataDomain = import("ethers").TypedDataDomain;
export type TypedDataField = import("ethers").TypedDataField;
export type AuthorizationRequest = import("ethers").AuthorizationRequest;
export type Authorization = import("ethers").Authorization;
export type AuthorizationLike = import("ethers").AuthorizationLike;
export type EvmTransactionReceipt = import("ethers").TransactionReceipt;
export type EvmTransactionResponse = import("ethers").TransactionResponse;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type TypedData = import("./src/wallet-account-read-only-evm.js").TypedData;
export type DelegationInfo = import("./src/wallet-account-read-only-evm.js").DelegationInfo;
export type EvmTransaction = import("./src/wallet-account-read-only-evm.js").EvmTransaction;
export type EvmGasOverrides = import("./src/wallet-account-read-only-evm.js").EvmGasOverrides;
export type EvmTransferOptions = import("./src/wallet-account-read-only-evm.js").EvmTransferOptions;
export type EvmWalletConfig = import("./src/wallet-account-read-only-evm.js").EvmWalletConfig;
export type EvmTransactionDetails = import("./src/wallet-account-read-only-evm.js").EvmTransactionDetails;
export type ApproveOptions = import("./src/wallet-account-evm.js").ApproveOptions;
export type EvmApproveOptions = import("./src/wallet-account-evm.js").EvmApproveOptions;
